# Generated by Django 4.2.3 on 2023-07-13 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flag',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='country_name',
        ),
    ]
