# Generated by Django 4.2.3 on 2023-07-13 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_rename_flag_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country_name',
            new_name='name',
        ),
    ]
